apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimerdinger-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - envFrom:
          - secretRef:
              name: heimerdinger-db-config
        image: postgresql-image:version
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
            - /usr/libexec/check-container
            - --live
          failureThreshold: 3
          initialDelaySeconds: 120
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 10
        name: postgresql
        ports:
        - containerPort: 5432
          protocol: TCP
        readinessProbe:
          exec:
            command:
            - /usr/libexec/check-container
          failureThreshold: 3
          initialDelaySeconds: 5
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            memory: 512Mi
        securityContext:
          capabilities: {}
          privileged: false
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /var/lib/pgsql/data
          name: heimerdinger-db-data
      volumes:
      - name: heimerdinger-db-data
        persistentVolumeClaim:
          claimName: heimerdinger-db